aliases:
	blacklist = bedrock, barrier

command /randomize <text>:
	permission: randomize.admin
	trigger:
		if arg-1 is crafting:
			if {randomize::crafting} is true:
				set {randomize::crafting} to false
				send "&cDisabled Randomize Crafting"
			else:
				set {randomize::crafting} to true
				send "&aEnabled Randomize Crafting"
on craft:
	if {randomize::crafting} is true:
		set {_i} to random item out of all items
		if {_i} is not blacklist:
			set event-slot to {_i}